name: Build and test scalellm package

on:
  workflow_dispatch:

  # Schedule the workflow to run at 00:00 (UTC) every day.
  schedule:
    - cron: '0 0 * * *'  

jobs:
  linux-gcc:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        build_type: [Release]
    
    runs-on: [self-hosted, linux, x64, build]
    
    env:
        BUILD_TYPE: ${{ matrix.build_type }}
        # Tells vcpkg where binary packages are stored.
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/../../ci_cache/.vcpkg/bincache
        # Tells ccache where to store its cache.
        CCACHE_DIR: ${{ github.workspace }}/../../ci_cache/.ccache

    steps:
    - name: Install toolkits
      run: |
        sudo apt-get install -y build-essential ninja-build bison gcc-12 g++-12 libunwind-dev python3-dev libboost-all-dev ccache
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12
  
    - name: Show gcc version
      run: gcc --version

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create cache directory
      run: |
        mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        mkdir -p $CCACHE_DIR
    
    - name: Zero out ccache statistics
      run: ccache -z

    - name: Build whl package
      run: |
        python setup.py bdist_wheel

    - name: Show ccache statistics
      run: ccache -s

    - name: Show whl package size
      run: du -h dist/*

    - name: Install the package
      run: |
        pip install dist/*.whl --force-reinstall

    - name: Run pytest
      run: pytest
