name: Build and test

on:
  push:
    paths:
      - "src/**"
      - "third_party/**"
      - "cmake/**"
      - "scalellm/**/*.cpp"
      - "scalellm/**/*.h"
      - "**/CMakeLists.txt"
      - ".github/workflows/build.yml"
      - "vcpkg.json"
    branches: 
      - main

  pull_request:
    paths:
      - "src/**"
      - "third_party/**"
      - "cmake/**"
      - "scalellm/**/*.cpp"
      - "scalellm/**/*.h"
      - "**/CMakeLists.txt"
      - ".github/workflows/build.yml"
      - "vcpkg.json"
    branches:
      - main

  workflow_dispatch:

jobs:
  linux-gcc:
    strategy:
      matrix:
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        build_type: [Release]
    
    runs-on: [self-hosted, linux, x64, build]
    
    env:
        BUILD_TYPE: ${{ matrix.build_type }}
        # Tells vcpkg where binary packages are stored.
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/../../ci_cache/.vcpkg/bincache
        # Tells ccache where to store its cache.
        CCACHE_DIR: ${{ github.workspace }}/../../ci_cache/.ccache
        # Tells where to store the dependencies.
        DEPENDENCES_ROOT: ${{ github.workspace }}/../../ci_cache/.deps

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create cache directory
      run: |
        mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        mkdir -p $CCACHE_DIR
        mkdir -p $DEPENDENCES_ROOT

    - name: CMake Build in the 'build' subdirectory
      run: |
        ./tools/run_in_docker.sh -ni cmake -G Ninja -S . -B build -DCMAKE_CUDA_ARCHITECTURES=80
        ./tools/run_in_docker.sh -ni cmake --build build --config ${{env.BUILD_TYPE}} --target all

    # - name: benchmark
    #   if: ${{ env.BUILD_TYPE == 'Release' }}
    #   run: ./build/src/benchmark/micro_benchmark

    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ../tools/run_in_docker.sh -ni -o --gpus=all ctest --output-on-failure -C ${{env.BUILD_TYPE}}
